-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Perheenjasen CASCADE;
DROP TABLE IF EXISTS Askare CASCADE;
DROP TABLE IF EXISTS Luokka CASCADE;
DROP TABLE IF EXISTS LuokanAskareet CASCADE;

